#![allow(dead_code)]
/// Demo example generated by ChatGPT, followed by intensive debugging of the `syn` logic in the proc macro.
//# Purpose: Demo the use of proc macros to generate constants at compile time
// "use thag_demo_proc_macros..." is a "magic" import that will be substituted by proc_macros.proc_macro_crate_path
// in your config file or defaulted to "demo/proc_macros" relative to your current directory.
use thag_demo_proc_macros::HostPortConst;

#[derive(HostPortConst)]
struct Config {
    #[const_value = "localhost"]
    hostname: &'static str,
    #[const_value = "8080"]
    port: u16,
}

fn main() {
    println!("Hostname: {}", Config::HOSTNAME);
    println!("Port: {}", Config::PORT);
}
